//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class MSEsystemEntities1 : DbContext
{
    public MSEsystemEntities1()
        : base("name=MSEsystemEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Category> Category { get; set; }
    public virtual DbSet<Department> Department { get; set; }
    public virtual DbSet<Domain> Domain { get; set; }
    public virtual DbSet<Location> Location { get; set; }
    public virtual DbSet<Role> Role { get; set; }
    public virtual DbSet<Status> Status { get; set; }
    public virtual DbSet<Task> Task { get; set; }
    public virtual DbSet<Ticket> Ticket { get; set; }
    public virtual DbSet<User> User { get; set; }
    public virtual DbSet<UserTicket> UserTicket { get; set; }
    public virtual DbSet<UserDomain> UserDomain { get; set; }

    public virtual ObjectResult<spGetData_Result> spGetData(Nullable<int> userId)
    {
        var userIdParameter = userId.HasValue ?
            new ObjectParameter("userId", userId) :
            new ObjectParameter("userId", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetData_Result>("spGetData", userIdParameter);
    }
}
