//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieActor
    {
        public int MovieID { get; set; }
        public int ActorID { get; set; }
        public int MainActor { get; set; }
        public Nullable<bool> IsArchive { get; set; }
    }
}
